[package]
name = "site"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
tera = "0.11"
glob = "0.2"
rayon = "1"
serde = "1"
serde_derive = "1"
sass-rs = { path = "../../../sass-rs" }

errors = { path = "../errors" }
config = { path = "../config" }
utils = { path = "../utils" }
templates = { path = "../templates" }
front_matter = { path = "../front_matter" }
pagination = { path = "../pagination" }
taxonomies = { path = "../taxonomies" }
content = { path = "../content" }
search = { path = "../search" }
imageproc = { path = "../imageproc" }

[dev-dependencies]
tempfile = "3"
